### ISSUE TITLE
TO-DO: Cleanup, Revision, and Styling

### ISSUE THREAD

**Issue by iamdrewkirkland** [nss-day-cohort-39/tabloid-full-stack-velours#128]
### all the little things we'd like to get to, but aren't _broken_
- [x] Include SQL customization to default SQL scripts
- [x] Raise errors on invalid inputs (new post, edit post, login, register)
- [x] Clear inputs after successful entry (category and tag)
- [x] submit form via ENTER key for forms (new post, edit post, login, register)
- [ ] resize default user image for user profile
- [ ] make sure email & username is unique to register
- [ ] add alert for deleting tags and categories to confirm delete 
- [ ] resize buttons on post detail
